import turtle
mnau = turtle.Turtle()
turtle.title("Mnau<3")
strana = input("Vyber si stranu[boční(b), přední(p)]: ")
def noha():
    mnau.fillcolor("black")
    mnau.begin_fill()
    for i in range(2):
        mnau.fd(20)
        mnau.rt(90)
        mnau.fd(20)
        mnau.rt(90)
    mnau.end_fill()
    mnau.penup()
    mnau.rt(90)
    mnau.fd(20)
    mnau.lt(90)
    mnau.pendown()
    for i in range(2):
        mnau.fd(20)
        mnau.rt(90)
        mnau.fd(20)
        mnau.rt(90)  
if strana == "b":
    mnau.begin_fill()
    for j in range(2):
        mnau.lt(90)
        mnau.fd(100)
        mnau.lt(90)
        mnau.fd(300)
    mnau.end_fill()
    mnau.penup()
    mnau.goto(-280, 0)
    mnau.pendown()
    noha()
    mnau.penup()
    mnau.goto(-40,0 )
    mnau.pendown()
    noha()
    mnau.penup()
    mnau.goto(0, 60)
    mnau.pendown()
    mnau.begin_fill()
    mnau.lt(90)
    mnau.fd(10)
    mnau.rt(120)
    mnau.fd(50)
    mnau.rt(90)
    mnau.fd(10)
    mnau.rt(90)
    mnau.fd(50)
    mnau.end_fill()
    mnau.begin_fill()
    mnau.bk(50)
    mnau.rt(130)
    mnau.fd(60)
    mnau.lt(90)
    mnau.fd(10)
    mnau.lt(90)
    mnau.fd(60)
    mnau.end_fill()
    mnau.bk(60)
    mnau.rt(180)
    mnau.fd(10)
    mnau.rt(90)
    mnau.fd(10)
    mnau.rt(90)
    mnau.fd(10)
    mnau.penup()
    mnau.goto(-300,60)
    mnau.pendown()
    mnau.begin_fill()
    mnau.rt(110)
    for t in range(3):
        mnau.fd(80)
        mnau.lt(90)
    mnau.fd(80)
    mnau.end_fill()
    mnau.penup()
    mnau.lt(90)
    mnau.fd(80)
    mnau.pendown()
    mnau.fd(10)
    mnau.lt(90)
    mnau.fd(30)
    mnau.lt(90)
    mnau.fd(10)
    mnau.penup()
    mnau.rt(90)
    mnau.fd(50)
    mnau.lt(90)
    mnau.fd(60)
    mnau.pendown()
    mnau.begin_fill()
    mnau.rt(90)
    for h in range(2):
        mnau.fd(10)
        mnau.lt(90)
    mnau.fd(10)
    mnau.end_fill()
    mnau.rt(180)
    mnau.fd(10)
    for g in range(2):
        mnau.lt(90)
        mnau.fd(10)
    mnau.penup()
    mnau.goto(-200, 0)
    mnau.pendown()
    mnau.fillcolor("white")
    mnau.begin_fill()
    mnau.lt(90)
    mnau.fd(20)
    mnau.rt(90)
    mnau.fd(100)
    mnau.rt(90)
    mnau.fd(20)
    mnau.end_fill()    
    mnau.hideturtle()
    turtle.done()
#if strana == "p":
